- name: Data Domain Playbook.
  hosts: dd
  connection: local
  gather_facts: false

  vars_files:
    - vars/credentials.yaml

  tasks:

# Delete DDVE 
    - name: "Delete Virtual Machine  {{vmname}}"
      vmware_guest:
        hostname: "{{ vc_hostname }}"
        username: "{{ vc_username }}"
        password: "{{vc_password }}"
        validate_certs: "{{ validate_certs }}"
        name: "{{ vmname }}"
        template: "{{ vm_template }}"
        datacenter: "{{ datacenter }}"
        esxi_hostname: "{{ esxi_host }}"
        folder: 'vm'
        datastore: "{{ datastore }}"
        force: yes
        state: absent
