# Martin.Flint@dell.com
- name: Data Domain Playbook.
  hosts: dd
  connection: local
  gather_facts: false

  vars_files:
    - vars/credentials.yaml

  tasks:

# DEPLOY THE DDVE IN VCENTER, didn't deploy the OVA because it takes too long configuring SSL keys on first boot
    - name: "Deploy Virtual Machine  {{vmname}}"
      vmware_guest:
        hostname: "{{ vc_hostname }}"
        username: "{{ vc_username }}"
        password: "{{vc_password }}"
        validate_certs: "{{ validate_certs }}"
        name: "{{ vmname }}"
        template: "{{ vm_template }}"
        datacenter: "{{ datacenter }}"
        esxi_hostname: "{{ esxi_host }}"
        folder: 'vm'
        datastore: "{{ datastore }}"
        state: poweredon

# WAIT FOR HTTPS RESPONSE FROM POWERPROTECT DATA DOMAIN
    - name: " {{vmname}} - Waiting for HTTPS connectivity."
      wait_for:
        host: "{{ddve_ip}}"
        port: 443
        state: started
        delay: 1
        sleep: 60
        timeout: 600
      register: waitforddve

# AUTHENTICATE TO DDVE REST API
    - name: "( {{ddve_ip}} ): Authenticate to PowerProtect DD REST API"
      uri:
        url: https://{{ddve_ip}}:3009/rest/v1.0/auth
        method: POST
        force_basic_auth: no
        validate_certs: no
        return_content: yes
        body_format: json
        body: |
          {
            "username": "sysadmin",
            "password": "{{dd_password}}"
          }
        status_code: 201
      register: dd_token


# SET THE SYSTEM PASSPHRASE
    - name: "( {{ddve_ip}} ): Set the system passphrase"
      uri:
        url: https://{{ddve_ip}}:3009/rest/v3.0/dd-systems/0/systems
        method: PUT
        headers:
          X-DD-AUTH-TOKEN: "{{dd_token.x_dd_auth_token}}"
          Content-Type: "application/json"
        force_basic_auth: no
        validate_certs: no
        body_format: json
        body: |
          {
            "operation": "set_pphrase",
            "pphrase_request": {
              "new_pphrase": "{{dd_password}}"
            }
          }
        return_content: yes
        status_code: 200
      register: passphrase


    - name: Set email address for alerts, detailed-autosupport and daily alert summary emails
      dellemc.datadomain.config:
        state: set
        option: admin-email
        admin-email: "{{ admin_email }}"

    - name: Set the location
      dellemc.datadomain.config:
        state: set
        option: location
        location: "{{ rack_location }}" # This could be RACK location, no spaces accepted!!!!

    - name: Add time servers
      dellemc.datadomain.ntp:
          state: add
          timeserver: "{{ ntp_servers }}"

    - name: enable the NTP local server
      dellemc.datadomain.ntp:
          state: enable

    - name: Set the mail (SMTP) server
      dellemc.datadomain.config:
        state: set
        option: mailserver
        mailserver: "{{ smtp_server }}" # SMTP server IP/hostname

    - name: Set the timezone 
      dellemc.datadomain.config:
        state: set
        option: timezone
        timezone: "{{ TZ }}"

    - name:  Create a filesystem on active tier storage
      dellemc.datadomain.filesys:
          state: create

    - name:  Enable filesystem Operations
      dellemc.datadomain.filesys:
          state: enable

    - name:  Set the Clean Schedule
      dellemc.datadomain.filesys:
          state: set
          operation: clean
          clean:
              schedule: "{{ clean_sched }}"
               
    - name: Create a MTree
      dellemc.datadomain.mtree:
          state: create
          mtree-path: "{{ export_path }}"
          quota:
              quota-soft-limit: 200 GiB
              quota-hard-limit: 250 GiB

    - name: Enable NFS clients to connect
      dellemc.datadomain.nfs:
          state: enable
        
    - name: Create an export, and add clients
      dellemc.datadomain.nfs:
          state: create
          export-name: "{{ export_name }}"
          path: "{{ export_path }}"
          clients: "{{ client_network }}"
          options: "{{ export_options }}"
          # Even if Path does not exists, nfs share will be created. So use MTree module to create it.

    - name: Enable ddboost
      dellemc.datadomain.ddboost:
          state: enable

    - name:  Add a new ddboost user
      dellemc.datadomain.users:
          state: add
          user-name: "{{ ddbusername }}"
          role-name: "{{ ddbrole }}"
          user-password: "{{ dd_password }}"
          dd-password: "{{ dd_password }}"


    - name: Create the ddboost storage unit
      dellemc.datadomain.ddboost:
          state: create
          storage-unit: "{{ ddstorage_unit }}"
          user-name: "{{ ddbusername }}"
          ## Optional parameters
          quota:
              quota-soft-limit: 10 GiB
              quota-hard-limit: 15 GiB
              report-physical-size: 10 GiB
          stream-limit:
              write-stream-soft-limit: 10 # or none - remove limit
              read-stream-soft-limit: 15 # or none - remove limit
              repl-stream-soft-limit: 13 # or none - remove limit
              combined-stream-soft-limit: 20 # or none - remove limit
              combined-stream-hard-limit: 20 # or none - remove limit          

    - name: Assign the username to the ddboost protocol
      dellemc.datadomain.ddboost:
          state: assign
          user-name: "{{ ddbusername }}"


# LOGOUT OF THE REST API
    - name: "( {{ddve_ip}}): Logout of the REST API"
      uri:
        url: https://{{ddve_ip}}:8443/api/v2/logout
        headers:
          Authorization: "Bearer {{token.json.access_token}}"
          Content-Type: "application/json"
        method: POST
        validate_certs: no
        return_content: yes
        body_format: json
        status_code: 204