---
# tested with ansible 2.14.3 on Ubuntu 22.04.1 LTS, master and workers running centos 7
# martin.flint@dell.com

- hosts: all

  become: true

  tasks: 
 

  - name: Deploy Quake Server
    when: inventory_hostname in groups['k8s_master']
    shell: "kubectl apply -f https://raw.githubusercontent.com/DTW2023/IaC/main/8%20-%20Fun/qk/quake.yaml"

