# martin.flint@dell.com
---
- name: Deploy PowerScale Virtual Machines
  hosts: localhost
  connection: local
  gather_facts: no

  vars_files:
    - vm_vars.yml

  tasks:

    - name: Deploy Virtual Machines
      vmware_guest:
        hostname: "{{ vc_hostname }}"
        resource_pool: "{{ rp }}"
        username: "{{ vc_username }}"
        password: "{{vc_password }}"
        validate_certs: "{{ validate_certs }}"
        name: "{{ item.host_name }}"
        template: "{{ item.vm_template }}"
        datacenter: "{{ item.datacenter }}"
        esxi_hostname: "{{ item.esxi_host }}"
        folder: 'vm'
        datastore: "{{ item.datastore }}"
        state: poweredon
      loop: "{{ guests }}"
      loop_control:
        pause: 2