---
apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: fio
spec:
  serviceName: fio
  replicas: 1
  selector:
    matchLabels:
      app: fio
  template:
    metadata:
      labels:
        app: fio
    spec:
      containers:
      - name: fio
        image: joshuarobinson/fio:3.19
        command: ["fio"]
        args: ["/configs/fio.job", "--eta=never", "--filename_format=$jobnum.$filenum", "--directory=/scratch/"]
        volumeMounts:
        - name: fio-config-vol
          mountPath: /configs
        - name: fio-data
          mountPath: /scratch
      volumes:
      - name: fio-config-vol
        configMap:
          name: fio-job-config
  volumeClaimTemplates:
  - metadata:
      name: fio-data
    spec:
      storageClassName: powerscale
      accessModes:
      - ReadWriteOnce
      resources:
        requests:
          storage: 4Ti
