---
# Thanks to clifford.rodriguez@dell.com and go to https://github.com/SkunkworksAutomation for all automation things for DPS
# also check out https://github.com/dell/ansible-datadomain

- name: "PowerProtect Data Domain & Data Manager stack deployment demo"
  hosts: localhost
  collections:
    - community.vmware
  become: no
  gather_facts: false

  vars:
  vars_files:
    - credentials.yaml

  tasks:

# I have cheated here! I have a pre-configured DD that I use and deploy that, to save some time in the demo.
# However go over to https://github.com/SkunkworksAutomation and this has details on how to deploy from an ova image
# also the ansible modules from DD work well and are available at https://github.com/dell/ansible-datadomain
# one thing to note about the ansible modules is nothing to set the "passphrase" check out 
# https://github.com/SkunkworksAutomation/PowerProtectDD/blob/main/Ansible/ddmc-01.yml line 206

# for all things on https://github.com/SkunkworksAutomation contact clifford.rodriguez@dell.com
# for the DD modules on https://github.com/dell/ansible-datadomain contact sudarshan.kshirsagar@virtustream.com


# DEPLOY THE DDVE IN VCENTER, didn't deploy the OVA because it takes too long configuring SSL keys on first boot
  - name: "Deploy Virtual Machine  {{ddvmname}}"
    vmware_guest:
       hostname: "{{ vcenter_host }}"
       username: "{{ vc_username }}"
       password: "{{ vc_password }}"
       validate_certs: "{{ validate_certs }}"
       name: "{{ ddvmname }}"
       template: "{{ ddvm_template }}"
       datacenter: "{{ vcenter_dc }}"
       esxi_hostname: "{{ vcenter_esx }}"
       folder: 'vm'
       datastore: "{{ vcenter_ds }}"
       state: poweredon

# WAIT FOR HTTPS RESPONSE FROM POWERPROTECT DATA DOMAIN
  - name: " {{ddvmname}} - Waiting for HTTPS connectivity."
    wait_for:
      host: "{{ddve_ip}}"
      port: 443
      state: started
      delay: 1
      sleep: 60
      timeout: 600
    register: waitforddve