kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: pvcprometheusalertmanager
  namespace: dell-observability-csm
spec:
  accessModes:
  - ReadWriteOnce
  resources:
    requests:
      storage: 2Gi
  storageClassName: nfs-csi
---
kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: pvcprometheuspushgateway
  namespace: dell-observability-csm
spec:
  accessModes:
  - ReadWriteOnce
  resources:
    requests:
      storage: 2Gi
  storageClassName: nfs-csi
---
kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: pvcprometheusserver
  namespace: dell-observability-csm
spec:
  accessModes:
  - ReadWriteOnce
  resources:
    requests:
      storage: 8Gi
  storageClassName: nfs-csi
