#!/bin/sh

#kubectl create namespace karavi
kubectl create namespace dell-observability-csm
kubectl apply --validate=false -f https://github.com/jetstack/cert-manager/releases/download/v1.10.0/cert-manager.crds.yaml
curl -fsSL -o /tmp/get_helm.sh https://raw.githubusercontent.com/helm/helm/main/scripts/get-helm-3
sh /tmp/get_helm.sh
helm repo add dell https://dell.github.io/helm-charts

# pull powerstore-config from powerstore-csi driver namespace
kubectl get secret powerstore-config -n powerstore-csi -o yaml | sed 's/namespace: powerstore-csi/namespace: dell-observability-csm/' | kubectl create -f -

# pull isilon-creds from powerscale-csi driver namespace
kubectl get secret isilon-creds -n powerscale-csi -o yaml | sed 's/namespace: powerscale-csi/namespace: dell-observability-csm/' | kubectl create -f -
helm install karavi-observability dell/karavi-observability -n dell-observability-csm -f values.yaml

helm repo add prometheus-community https://prometheus-community.github.io/helm-charts
helm repo add stable https://charts.helm.sh/stable
helm repo update


helm install prometheus prometheus-community/prometheus -n dell-observability-csm -f prometheus-values.yaml


helm repo add grafana https://grafana.github.io/helm-charts
helm repo update

helm install grafana grafana/grafana -n dell-observability-csm -f grafana-values.yaml




#copy and paste these into json panel...
#https://raw.githubusercontent.com/dell/karavi-observability/main/grafana/dashboards/powerstore/volume_io_metrics.json
#https://raw.githubusercontent.com/dell/karavi-observability/main/grafana/dashboards/powerstore/filesystem_io_metrics.json
#https://raw.githubusercontent.com/dell/karavi-observability/main/grafana/dashboards/powerstore/storage_consumption.json
#https://raw.githubusercontent.com/dell/karavi-observability/main/grafana/dashboards/topology/topology.json

