---
# Thanks to clifford.rodriguez@dell.com and go to https://github.com/SkunkworksAutomation for all automation things for DPS
# also check out https://github.com/dell/ansible-datadomain

- name: "PowerProtect Data Domain & Data Manager stack deployment demo"
  hosts: localhost
  collections:
    - community.vmware
  become: no
  gather_facts: false

  vars:
  vars_files:
    - credentials.yaml

  tasks:


# DEPLOY THE DDVE IN VCENTER, didn't deploy the OVA because it takes too long configuring SSL keys on first boot
  - name: "Deploy Virtual Machine  {{ddvmname}}"
    vmware_guest:
       hostname: "{{ vcenter_host }}"
       username: "{{ vc_username }}"
       password: "{{ vc_password }}"
       validate_certs: "{{ validate_certs }}"
       name: "{{ ddvmname }}"
       template: "{{ ddvm_template }}"
       datacenter: "{{ vcenter_dc }}"
       esxi_hostname: "{{ vcenter_esx }}"
       folder: 'vm'
       datastore: "{{ vcenter_ds }}"
       state: poweredon

# WAIT FOR HTTPS RESPONSE FROM POWERPROTECT DATA DOMAIN
  - name: " {{ddvmname}} - Waiting for HTTPS connectivity."
    wait_for:
      host: "{{ddve_ip}}"
      port: 443
      state: started
      delay: 1
      sleep: 60
      timeout: 600
    register: waitforddve