# metallb.yaml
apiVersion: metallb.io/v1beta1
kind: IPAddressPool
metadata:
  name: first-pool
  namespace: metallb-system
spec:
  addresses:
  # change IP ranges to suit your needs
  - 10.204.20.171-10.204.20.175