# tested with ansible 2.14.3 on Ubuntu 22.04.1 LTS, powerstore OS 3
---
- name: Deploy PowerStore Volume
  hosts: all
  connection: local
  gather_facts: no

  vars_files:
    - ps_vars.yaml

  tasks:

    - name: "Add hosts to powerstore"
      dellemc.powerstore.host:
        password: "{{ password }}"
        array_ip: "{{ array_ip }}"
        user: "{{ user }}"
        verifycert: "{{ verifycert }}"
        os_type: 'ESXi'
        detailed_initiators:
          - port_name: "{{ item.port_name }}"
            port_type: 'iSCSI'
        state: present
        initiator_state: 'present-in-host'
        host_name: "{{ item.host_name }}"
      loop:  "{{ esxi_hosts }}"

    - name: Create Host Group 
      dellemc.powerstore.hostgroup:
        password: "{{ password }}"
        array_ip: "{{ array_ip }}"
        user: "{{ user }}"
        verifycert: "{{ verifycert }}"
        hostgroup_name: "{{ hg_name }}"
        host_state: 'present-in-group'
        state: present
        hosts: "{{ item.host_name }}"
      loop: "{{ esxi_hosts }}"


    - name: Creating PowerStore Volume
      dellemc.powerstore.volume:
        password: "{{ password }}"
        array_ip: "{{ array_ip }}"
        user: "{{ user }}"
        verifycert: "{{ verifycert }}"
        vol_name: "{{ vol_name }}"
        size: "{{ vol_size }}"
        cap_unit: "{{ vol_capunit }}"
        state: 'present'
        mapping_state: 'mapped'
        hostgroup: "{{ hg_name }}"
        description: "{{ vol_desc }}"
      register: wwn_details

    - name: Saving WWN of powerstore Volume into a variable
      set_fact:
        volume_wwn:  "{{ wwn_details.volume_details.wwn}}"


    - name: enable iSCSI on ESXi hosts
      community.vmware.vmware_host_iscsi:
        hostname: "{{ vc_hostname }}"
        username: "{{ vc_username }}"
        password: "{{ vc_password }}"
        validate_certs: "{{ validate_certs }}"
        esxi_hostname: "{{ item.host_name }}"
        state: enabled
      loop: "{{ esxi_hosts }}"

    - name: Add Dynamic target iSCSI IP {{ iscsi_target_ip1 }} on ESXi hosts
      community.vmware.vmware_host_iscsi:
        hostname: "{{ vc_hostname }}"
        username: "{{ vc_username }}"
        password: "{{ vc_password }}"
        validate_certs: "{{ validate_certs }}"
        esxi_hostname: "{{ item.host_name }}"
        iscsi_config:
          vmhba_name: "{{ item.hba }}"
          send_target:
            address: "{{ iscsi_target_ip1 }}"
        state: present
      loop: "{{ esxi_hosts }}"

    - name: Add Dynamic target iSCSI IP {{ iscsi_target_ip2 }} on ESXi hosts
      community.vmware.vmware_host_iscsi:
        hostname: "{{ vc_hostname }}"
        username: "{{ vc_username }}"
        password: "{{ vc_password }}"
        validate_certs: "{{ validate_certs }}"
        esxi_hostname: "{{ item.host_name }}"
        iscsi_config:
          vmhba_name: "{{ item.hba }}"
          send_target:
            address: "{{ iscsi_target_ip1 }}"
        state: present
      loop: "{{ esxi_hosts }}"

    - name: Rescan ESXi hosts Storage Adapters
      vmware_host_scanhba:
        hostname: "{{ vc_hostname }}"
        username: "{{ vc_username }}"
        password: "{{ vc_password }}"
        validate_certs: "{{ validate_certs }}"
        esxi_hostname: "{{ item.host_name }}"
        refresh_storage: true
      loop: "{{ esxi_hosts }}"


    - name: Add VMware PowerStore datastore to nodes in cluster
      vmware_host_datastore:
        hostname: "{{ vc_hostname }}"
        username: "{{ vc_username }}"
        password: "{{ vc_password }}"
        validate_certs: "{{ validate_certs }}"
        datastore_name: "{{ new_datastore }}"
        datastore_type: 'vmfs'
        vmfs_device_name: '{{ volume_wwn }}'
        vmfs_version: 6
        esxi_hostname: "{{ esxi_hosts[0].host_name }}"
        state: present
