- hosts: localhost
  connection: local
  vars_files:
    - vars.yaml

  tasks:
    - name: Import Grafana dashboard
      community.grafana.grafana_dashboard:
        grafana_url: "{{ grafana_url }}"
        grafana_user: "{{ grafana_user }}"
        grafana_password: "{{ grafana_password }}"
        state: present
        org_id: 1
        commit_message: Updated by ansible
        overwrite: yes
        path: "{{ item.url }}"
      loop: "{{ json_dashboard }}"
