#!/bin/sh

# this script assumes powerstore csi name space is called 'powerstore-csi'
# it also assumes the powercale csi name space is called 'powerscale-csi'
# this cript does powerstore and powerscale, didn't have access to a powrflex to add that too!
# run this on master node!!!!!!!!!!!!!!!

# creates a newspace
kubectl create namespace dell-observability-csm

# installs a cert manager
kubectl apply --validate=false -f https://github.com/jetstack/cert-manager/releases/download/v1.10.0/cert-manager.crds.yaml

# uncomment these if helm is not installed already!!
#curl -fsSL -o /tmp/get_helm.sh https://raw.githubusercontent.com/helm/helm/main/scripts/get-helm-3
#sh /tmp/get_helm.sh

# Add Dell Delm Charts
helm repo add dell https://dell.github.io/helm-charts

# pull powerstore-config from powerstore-csi driver namespace
kubectl get secret powerstore-config -n powerstore-csi -o yaml | sed 's/namespace: powerstore-csi/namespace: dell-observability-csm/' | kubectl create -f -


# pull isilon-creds from powerscale-csi driver namespace
kubectl get secret isilon-creds -n powerscale-csi -o yaml | sed 's/namespace: powerscale-csi/namespace: dell-observability-csm/' | kubectl create -f -

# install karavi-observability
helm install karavi-observability dell/karavi-observability -n dell-observability-csm -f https://raw.githubusercontent.com/DTW2023/IaC/main/Misc/Dell%20CSM%20Observability%20install%20notes/values.yaml

# prometheus
helm repo add prometheus-community https://prometheus-community.github.io/helm-charts
helm repo add stable https://charts.helm.sh/stable
helm repo update
helm install prometheus prometheus-community/prometheus -n dell-observability-csm -f https://raw.githubusercontent.com/DTW2023/IaC/main/Misc/Dell%20CSM%20Observability%20install%20notes/prometheus-values.yaml

# Grafana
helm repo add grafana https://grafana.github.io/helm-charts
helm repo update
helm install grafana grafana/grafana -n dell-observability-csm -f https://raw.githubusercontent.com/DTW2023/IaC/main/Misc/Dell%20CSM%20Observability%20install%20notes/grafana-values.yaml

#prometheus_port=`kubectl get svc -n dell-observability-csm | grep prometheus-server | awk '{ print $5 }'| cut -f2 -d: | cut -f1 -d"/"`
#server_ip=`kubectl get pods -n dell-observability-csm -o wide | grep prometheus-server | awk '{ print $7 }'`
#echo prometheus server is at http://${server_ip}:${prometheus_port}
#echo""
#grafana_port=`kubectl get svc -n dell-observability-csm | grep ^grafana | awk '{ print $5 }'| cut -f2 -d: | cut -f1 -d"/"`
#grafana_ip=`kubectl get pods -n dell-observability-csm -o wide | grep ^grafana | awk '{ print $7 }'`
grafana_ip=`kubectl get svc -n dell-observability-csm grafana --no-headers | awk '{ print $4 }'`
grafana_port=80
PSWD=`kubectl get secret --namespace dell-observability-csm grafana -o jsonpath="{.data.admin-password}" | base64 --decode ; echo`
echo grafana server is at http://${grafana_ip}:${grafana_port} use you brower and login default is admin, and the password is $PSWD 
echo ""
echo Now, follow the steps from this section of the Dell CSM Observability Installation in DETAIL video at https://youtu.be/KY3NjHmGX-8?t=544
echo once configured install the approprite dashboards which you can get form here https://dell.github.io/csm-docs/docs/observability/deployment/#importing-csm-for-observability-dashboards
