---
# tested with ansible 2.14.3 on Ubuntu 22.04.1 LTS, master and workers running centos 7
# martin.flint@dell.com

- hosts: localhost
  tasks:

  - name: Deploy Kubernetes Dashboard
    kubernetes.core.k8s:
      state: present
      src: https://raw.githubusercontent.com/DTW2023/IaC/main/8%20-%20Fun/db/dashboard.yaml

  - name: Create Service Account for Kubernetes Dashboard
    kubernetes.core.k8s:
      state: present
      src: https://raw.githubusercontent.com/DTW2023/IaC/main/8%20-%20Fun/db/admin-user.yaml

  - name: get token
    command: "kubectl -n kubernetes-dashboard create token admin-user"
    register: token

  - name: Display Token
    debug:
      var: token.stdout_lines[0]

  - name: saving Token to file /root/IaC/Token
    copy:
      content: "{{ token.stdout_lines[0] }}"
      dest: /root/IaC/Token

  - name: run commmand
    debug:
      msg: run command 'kubectl -n kubernetes-dashboard create token admin-user' then goto https://10.204.20.175/ and use this token "{{ token.stdout_lines[0] }}"
