---
# Thanks to clifford.rodriguez@dell.com and go to https://github.com/SkunkworksAutomation for all automation things for DPS
# also check out https://github.com/dell/ansible-datadomain

- name: "Configure PPDM to Backup minecraft namespace and Virtual Machines master, worker-01, worker-02, worker-03"
  hosts: localhost
  collections:
    - community.vmware
  become: no
  gather_facts: false

  vars:
  vars_files:
    - credentials.yaml

  tasks:


# WAIT FOR HTTPS RESPONSE FROM POWERPROTECT DATA DOMAIN
  - name: " {{ddvmname}} - Waiting for HTTPS connectivity."
    wait_for:
      host: "{{ddve_ip}}"
      port: 443
      state: started
      delay: 1
      sleep: 60
      timeout: 600
    register: waitforddve

   

# AUTHENTICATE TO THE POWERPROTECT REST API & GRAB ACCESS TOKEN
  - name: "( {{ppdm_ip}} ): Authenticate to PowerProtect DM Rest API"
    uri:
      url: "https://{{ ppdm_ip }}:8443/api/v2/login"
      method: POST
      validate_certs: no
      return_content: yes
      body_format: json
      body:
        username: "{{ ppdm_id }}"
        password: "{{ppdm_pwd}}"
      status_code: 200
    register: token

  - name:
    debug:
      var: token.json.access_token

# GET THE INITIAL CONFIGURATION ID
  - name: "( {{ppdm_host}} ): Get the initial PowerProtect configuration"
    uri:
      url: https://{{ppdm_host}}:8443/api/v2/configurations
      headers:
        Authorization: "Bearer {{token.json.access_token}}"
        Content-Type: "application/json"
      method: GET
      validate_certs: no
      return_content: yes
      body_format: json
    register: config

  - name:
    debug:
      var: config.json.content[0].id

# GET THE CONFIG STATUS
  - name: "( {{ppdm_host}} ): Check the PowerProtect config status to see if it is complete"
    uri:
      url: https://{{ppdm_host}}:8443/api/v2/configurations/{{config.json.content[0].id}}/config-status
      headers:
        Authorization: "Bearer {{token.json.access_token}}"
        Content-Type: "application/json"
      method: GET
      validate_certs: no
      return_content: yes
      body_format: json
    register: monitor
    until: monitor.status == 200 and monitor.json.percentageCompleted == 100
    retries: 180
    delay: 10

# ENABLE VMware and K8s ASSET SOURCE
  - name: "( {{ppdm_host}} ): Enable VMware AND k8S asset source"
    uri:
      url: https://{{ppdm_host}}:8443/api/v2/common-settings/ASSET_SETTING
      headers:
        Authorization: "Bearer {{token.json.access_token}}"
        Content-Type: "application/json"
      method: PUT
      validate_certs: no
      return_content: yes
      body_format: json
      body: |
          {
              "id": "ASSET_SETTING",
              "properties": [
                  {
                      "name": "enabledAssetTypes",
                      "type": "LIST",
                      "value": "VMWARE_VIRTUAL_MACHINE,KUBERNETES"
                  }
              ]
          }
      status_code: 200
    register: settings

# GET THE VCENTER CERTIFICATE
  - name: "( {{ppdm_host}} ): Get the vCenter Certificate using https://{{ppdm_host}}:8443/api/v2/certificates?host={{cluster_ip}}&port={{cluster_port}}&type=Root"
    uri:
      url: https://{{ppdm_host}}:8443/api/v2/certificates?host={{cluster_ip}}&port={{cluster_port}}&type=Root
      #https://{{ ppdm_ip }}:8443/api/v2/certificates?host={{ cluster_ip }}&port={{ cluster_port }}&type=Root
      headers:
        Authorization: "Bearer {{token.json.access_token}}"
        Content-Type: "application/json"
      method: GET
      validate_certs: no
      return_content: yes
      body_format: json
      #status_code: 200
    register: k8_cert
    # until: k8_cert.status == 200
    # retries: 90
    # delay: 10

  # - name:
  #   debug:
  #     var: k8_cert.json[0]

# ACCEPT THE  CERTIFICATE
  - name: "( {{ppdm_host}} ): Accept the Kubernetes certificate"
    uri:
      url: https://{{ppdm_host}}:8443/api/v2/certificates/{{k8_cert.json[0].id}}
      headers:
        Authorization: "Bearer {{token.json.access_token}}"
        Content-Type: "application/json"
      method: PUT
      validate_certs: no
      return_content: yes
      body_format: json
      body: |
          {
            "fingerprint": "{{k8_cert.json[0].fingerprint}}",
            "host": "{{k8_cert.json[0].host}}",
            "id": "{{k8_cert.json[0].id}}",
            "issuerName": "{{k8_cert.json[0].issuerName}}",
            "notValidAfter": "{{k8_cert.json[0].notValidAfter}}",
            "notValidBefore": "{{k8_cert.json[0].notValidBefore}}",
            "port": "{{k8_cert.json[0].port}}",
            "state": "ACCEPTED",
            "subjectName": "{{k8_cert.json[0].subjectName}}",
            "type": "{{k8_cert.json[0].type}}"
          }
      status_code: 200
    register: accept_k8_cert
    until: accept_k8_cert.status == 200
    retries: 90
    delay: 10

  - name:
    debug:
      var: accept_k8_cert.json

# create ppdm namespace
  - name: Create a k8s namespace ppdm
    kubernetes.core.k8s:
      name: ppdm
      api_version: v1
      kind: Namespace
      state: present

# Create a Service Account for PPDM
  - name: Create Service Account for PPDM
    kubernetes.core.k8s:
      state: present
      src: https://raw.githubusercontent.com/DTW2023/IaC/main/10%20-%20DPS%20-%20Part%20II/K8s/ppdm-user.yaml

# Generate Token for PPDM User
  - name: get token
    command: "kubectl -n ppdm create token ppdm-user"
    register: ppdm_token

# Show the token, this wiill be used to configure PPDM
  - name: Display Token
    debug:
      var: ppdm_token.stdout_lines[0]

  - name: "Add Credentials for Cluster {{ cluster_ip }} on {{ vmname }}"
    uri:
      url: "https://{{ ppdm_ip }}:8443/api/v2/credentials"
      headers:
        Authorization: "Bearer {{token.json.access_token}}"
        Content-Type: "application/json"
      method: POST
      validate_certs: no
      return_content: yes
      body_format: json
      status_code: [200,201,403]
      body: |
        {"type":"KUBERNETES","name":"{{ cluster_name }}","password":"{{ ppdm_token.stdout_lines[0] }}","method":"TOKEN"}
    register: kube_creds
    until: kube_creds.status == 200 or kube_creds.status == 201 or kube_creds.status == 403
    retries: 90
    delay: 10

  - name: kube_creds.json
    debug:
      var: kube_creds.json


  - name: "Add cluster {{ cluster_ip }} as a source on {{ vmname }}"
    uri:
      url: "https://{{ ppdm_ip }}:8443/api/v2/inventory-sources"
      headers:
        Authorization: "Bearer {{token.json.access_token}}"
        Content-Type: "application/json"
      method: POST
      validate_certs: no
      return_content: yes
      body_format: json
      status_code: 201
      body: |
        {"id":"","name":"{{ cluster_name }}","version":"","type":"KUBERNETES","lastDiscovered":"","address":"{{ cluster_ip }}","port":"{{ cluster_port }}","credentials":{"id":"{{ kube_creds.json.id }}"},"ssl":false,"details":{"k8s":{"vCenterId":null,"distributionType":"NON_VSPHERE","configurations":[]}},"_links":{}}
    register: kube_source

  - name:
    debug:
      var: kube_source.json

  - name: "Pause for 60 seconds for Initial Discovery for inventory source {{ cluster_name }}"
    ansible.builtin.pause:
      seconds: 60

#Create a ppdm-snapshot-storage-class-mapping for PPDM in namespace powerprotect
  - name: Create Service Account for PPDM in namespace powerprotect
    kubernetes.core.k8s:
      state: present
      src: https://raw.githubusercontent.com/DTW2023/IaC/main/10%20-%20DPS%20-%20Part%20II/K8s/snapshot-configmap.yaml


# LOGOUT OF THE REST API
#  - name: "( {{ ppdm_ip }}): Logout of the REST API"
#    uri:
#      url: "https://{{ ppdm_ip }}:8443/api/v2/logout"
#      headers:
#        Authorization: "Bearer {{token.json.access_token}}"
#        Content-Type: "application/json"
#      method: POST
#      validate_certs: no
#      return_content: yes
#      body_format: json
#      status_code: 204
