apiVersion: storage.dell.com/v1
kind: CSIPowerStore
metadata:
  name: test-powerstore
  namespace: test-powerstore
spec:
  driver:
    configVersion: v2.5.0
    replicas: 1
    dnsPolicy: ClusterFirstWithHostNet
    forceUpdate: false
    fsGroupPolicy: ReadWriteOnceWithFSType
    storageCapacity: true
    common:
      image: "dellemc/csi-powerstore:v2.5.0"
      imagePullPolicy: IfNotPresent
      envs:
        - name: X_CSI_POWERSTORE_NODE_NAME_PREFIX
          value: "csi"
        - name: X_CSI_FC_PORTS_FILTER_FILE_PATH
          value: "/etc/fc-ports-filter"
    sideCars:
      - name: external-health-monitor
        args: ["--monitor-interval=60s"]
      - name: provisioner
        args: ["--capacity-poll-interval=5m"]

    controller:
      envs:
        - name: X_CSI_HEALTH_MONITOR_ENABLED
          value: "true"
        - name: X_CSI_NFS_ACLS
          value: "0777"
    node:
      envs:
        - name: "X_CSI_POWERSTORE_ENABLE_CHAP"
          value: "true"
        - name: X_CSI_HEALTH_MONITOR_ENABLED
          value: "true"
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: powerstore-config-params
  namespace: test-powerstore
data:
  driver-config-params.yaml: |
    CSI_LOG_LEVEL: "debug"
    CSI_LOG_FORMAT: "JSON"    
